spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.corc: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: true